CREATE TABLE `data_film` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(100) NOT NULL COMMENT '名称',
  `type` enum('video','image','radio','story') NOT NULL COMMENT '类型',
  `first_category` varchar(10) NOT NULL COMMENT '第一分类',
  `second_category` varchar(10) NOT NULL COMMENT '第二分类',
  `third_category` varchar(10) NOT NULL COMMENT '第三分类',
  `cover` varchar(200) NOT NULL COMMENT '封面',
  `publish_date` timestamp NOT NULL COMMENT '发布时间',
  `translate_name` varchar(100) NOT NULL COMMENT '译名',
  `film_name` varchar(100) NOT NULL COMMENT '电影名',
  `release_age` year(4) NOT NULL COMMENT '发布年代',
  `origin_place` varchar(20) NOT NULL COMMENT '地区',
  `category` varchar(10) NOT NULL COMMENT '分类',
  `language` varchar(20) NOT NULL COMMENT '语言',
  `subtitle` varchar(100) NOT NULL COMMENT '字母',
  `release_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '发布日期',
  `video_format` int(11) NOT NULL COMMENT '视频格式',
  `video_size` int(11) NOT NULL COMMENT '视频大小',
  `file_size` int(11) NOT NULL COMMENT '文件大小',
  `time_length` int(11) NOT NULL COMMENT '时长',
  `director` varchar(100) NOT NULL COMMENT '导演',
  `actors` varchar(500) NOT NULL COMMENT '主演',
  `download_links` text NOT NULL COMMENT '下载链接',
  `from_url` varchar(500) NOT NULL COMMENT '来源地址',
  `score` int(11) NOT NULL COMMENT '评分',
  `like` int(11) NOT NULL COMMENT '点赞',
  `download_sum` int(11) NOT NULL COMMENT '下载次数',
  `browse_sum` int(11) NOT NULL COMMENT '浏览次数',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
